export const beerActionTypes = {
  LOAD_BEERS: 'LOAD_BEERS',
  LOAD_BEER: 'LOAD_BEER',
  FAILED_LOAD_BEERS: 'FAILED_LOAD_BEERS',
  FAILED_LOAD_BEER: 'FAILED_LOAD_BEER',
};

export const cartActionTypes = {
  BUY_CART: 'BUY_CART',
  LOAD_CART: 'LOAD_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_TO_CART: 'DELETE_TO_CART',
  FAILED_BUY_CART: 'FAILED_BUY_CART',
  FAILED_LOAD_CART: 'FAILED_LOAD_CART',
  FAILED_ADD_TO_CART: 'FAILED_ADD_TO_CART',
  FAILED_DELETE_TO_CART: 'FAILED_DELETE_TO_CART',
};
